### PR TITLE
webapi: add load and save snapshots

### PR DESCRIPTION
**Pull request by karlvr**
Following on from the discussion in #30, I've added the ability to call load and save snapshot via the web API. I've marked this as a draft as I've only just started trying this out... it is working nicely... I'd like to know if this is a type of PR that you'd be interested in receiving.

### CODE REVIEW

**Comment by floooh** [comment]
Surprisingly small fix :) I'll try to give it a whirl in the next few days and then merge (I'm currently in a different rabbit hole but still don't want to 'blindly' merge)

**Comment by karlvr** [comment]
@floooh thank you, I've added those and renamed the PR to better fit.

**Comment by karlvr** [comment]
A related question... I'm wondering about webapi without UI... I think I can see I could pull the snapshots out of the `CHIPS_USE_UI` section... is there a reason why webapi is dependent upon UI at the moment?

**Comment by floooh** [comment]
> is there a reason why webapi is dependent upon UI at the moment

No specific reason except that my VSCode extension sort-of depends on features of the UI debugger. Properly separating the two would be better, but from my PoV not a high priority.

**Comment by floooh** [comment]
Ok, merged. Apologies for the delay. Will look into the other PR now.

**Pull request merged**
